import csv
import os
from typing import Any, Dict
from supabase import create_client, Client  # type: ignore
from dotenv import load_dotenv  # type: ignore

load_dotenv()

# SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for bulk imports
url = os.environ.get("EXPO_PUBLIC_SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") # Service role key for bypass RLS

if not url or not key:
    print("[Error] EXPO_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY is missing from your .env file.")
    exit(1)

supabase: Client = create_client(url, key)

def import_institutions(file_path: str):
    """
    Import institutions from a CSV file into the Supabase 'institutions' table.
    Expects columns: name, type, registration_number, accredited, location
    """
    print(f"[Start] Starting import: {file_path}")
    
    with open(file_path, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        records: list[dict[str, Any]] = []
        for row in reader:
            # Type casting for bool
            if 'accredited' in row:
                row['accredited'] = row['accredited'].lower() == 'true'
            records.append(row)
        
        # Batch insert for performance
        batch_size = 500
        for i in range(0, len(records), batch_size):
            # Use list comprehension to avoid Pyre slicing issues
            batch = [records[j] for j in range(i, min(i + batch_size, len(records)))]
            try:
                supabase.table('institutions').insert(batch).execute()
                print(f"[OK] Imported batch {i // batch_size + 1}")
            except Exception as e:
                print(f"[Error] In batch {i // batch_size + 1}: {e}")

def import_professionals(file_path: str):
    """
    Import professionals from a CSV file into the Supabase 'professionals' table.
    Expects columns: full_name, profession, registration_number, is_verified, specialization
    """
    print(f"[Start] Starting import: {file_path}")
    
    with open(file_path, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        records: list[dict[str, Any]] = []
        for row in reader:
            if 'is_verified' in row:
                row['is_verified'] = row['is_verified'].lower() == 'true'
            records.append(row)
            
        batch_size = 500
        for i in range(0, len(records), batch_size):
            # Use list comprehension to avoid Pyre slicing issues
            batch = [records[j] for j in range(i, min(i + batch_size, len(records)))]
            try:
                supabase.table('professionals').insert(batch).execute()
                print(f"[OK] Imported batch {i // batch_size + 1}")
            except Exception as e:
                print(f"[Error] In batch {i // batch_size + 1}: {e}")

if __name__ == "__main__":
    # Import the pilot data generated by generate_pilot_samples.py
    up_csv = 'scripts/data/institutions_up.csv'
    uct_csv = 'scripts/data/institutions_uct.csv'
    
    if os.path.exists(up_csv):
        import_institutions(up_csv)
    if os.path.exists(uct_csv):
        import_institutions(uct_csv)
        
    print("[Info] Data Importer process complete.")
